input {
  udp {
    port => 5000
    codec => json_lines
  }
}
 
filter {
  date {
    match => ["log_timestamp", "dd.MM.yyyy HH:mm:ss"]
    target => "@timestamp"
    timezone => "Asia/Kolkata"
  }
 
  mutate {
    remove_field => ["@version", "host", "port"]
  }
}
 
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "logpro-logs"
  }
  stdout {
    codec => rubydebug
  }
}
 