# Generated by Django 6.0.5 on 2026-06-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=1)),
                ('thread', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'log_entry',
                'indexes': [models.Index(fields=['level'], name='log_entry_level_f502db_idx'), models.Index(fields=['timestamp'], name='log_entry_timesta_dc3333_idx'), models.Index(fields=['level', 'timestamp'], name='log_entry_level_7dd18f_idx')],
            },
        ),
    ]
