# Generated by Django 6.0.5 on 2026-06-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logentry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='log_entry_level_f502db_idx',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='log_entry_timesta_dc3333_idx',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='log_entry_level_7dd18f_idx',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
