# Generated by Django 6.0.5 on 2026-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_logentry_log_entry_level_f502db_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logconfig',
            name='app_name',
            field=models.CharField(default='logs', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logconfig',
            name='es_index',
            field=models.CharField(default='logpro-logs', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logconfig',
            name='log_format',
            field=models.CharField(default='opsman', max_length=50),
            preserve_default=False,
        ),
    ]
